[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.0.1"
description = ""
authors = []
include = ["src/manage.py"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.4"
gunicorn = "^20.1.0"
environs = "^9.5.0"

[tool.poetry.scripts]
{{cookiecutter.project_name}}-cli = "src.manage:main"
{{cookiecutter.project_name}}-server = "gunicorn.app.wsgiapp:run"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
